repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      # Linter
      - id: ruff
        args: [ --fix ]
      # Formatter
      - id: ruff-format

  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.21.0
    hooks:
      - id: sqlfmt
        language_version: python3
